# https://developer.wordpress.org/advanced-administration/server/web-server/nginx/
# https://github.com/spinupwp/wordpress-nginx/blob/develop/sites-available/single-site.com

location = /favicon.ico {
    return 404;
    log_not_found off;
    access_log off;
}

location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
}

# Deny all attempts to access hidden files such as .htaccess, .htpasswd, .DS_Store (Mac).
# location ~ /\.
location ~* /\.(?!well-known\/) {
    return 404;
    log_not_found off;
    access_log off;
}

# Deny access to any files with a .php extension in the uploads directory
# Works in sub-directory installs and also in multisite network
location ~* /(?:uploads|files)/.*\.php$ {
    return 404;
    log_not_found off;
    access_log off;
}

location / {
    # This is cool because no php is touched for static content.
    # include the "?$args" part so non-default permalinks doesn't break when using query string
    try_files $uri $uri/ /index.php?$args;
    # try_files $uri $uri/ =404;
}

location ~* \.(webp|woff2|mp4|png|jpg|jpeg|ico|svg|gif)$ {
    expires 1y;
    access_log off;
    log_not_found off;
}

location ~* \.(js|css)$ {
    expires 1d;
    access_log off;
    log_not_found off;
}

# Prevent access to certain file extensions
location ~\.(ini|log|conf|zip)$ {
    return 404;
    log_not_found off;
    access_log off;
}

# Hide Nginx version in error messages and reponse headers.
server_tokens off;

# The X-XSS-Protection header has been deprecated by modern browsers and its use can introduce additional security issues on the client side.
# As such, it is recommended to set the header as X-XSS-Protection: 0 in order to disable the XSS Auditor, and not allow it to take the default behavior of the browser handling the response.
# Please use Content-Security-Policy instead.
add_header X-XSS-Protection "0" always;

# .htaccess

add_header Content-Security-Policy "script-src * 'unsafe-inline' 'unsafe-eval'; object-src 'none'; worker-src 'none'; manifest-src 'none'; font-src 'self' https://fonts.gstatic.com; form-action 'self'; base-uri 'none';" always;
# Header always unset Access-Control-Allow-Origin
add_header X-Frame-Options "ALLOWALL" always;
add_header X-Content-Type-Options "nosniff" always;
# Header always unset Access-Control-Allow-Methods
add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), midi=(), ch-ua=(*), ch-ua-mobile=(*), ch-ua-arch=(*), ch-ua-platform=(*), ch-ua-model=(*), ch-ua-full-version=(*), ch-ua-platform-version=(*), ch-ua-bitness=(*), ch-ua-full-version-list=(*)" always;
add_header Referrer-Policy "strict-origin" always;

index index.php index.html;

location ~ \.php$ {
    # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini

    include fastcgi.conf;
    fastcgi_intercept_errors on;

    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # Will otherwise default to /var/www

    fastcgi_pass unix:/run/php/php8.3-fpm.sock;
}