# https://developer.wordpress.org/advanced-administration/server/web-server/nginx/
# https://github.com/spinupwp/wordpress-nginx/blob/develop/sites-available/single-site.com

location ~ ^/feed {
    return 404;
    log_not_found off;
    access_log off;
}
location ~ ^/wp-config {
    return 404;
    log_not_found off;
    access_log off;
}
location ~ ^/xmlrpc {
    return 404;
    log_not_found off;
    access_log off;
}
location ~ ^/sessions {
    return 404;
    log_not_found off;
    access_log off;
}
location ~* /\.(?!well-known\/) {
    return 404;
    log_not_found off;
    access_log off;
}
location ~* /(?:uploads|files)/.*\.php$ {
    return 404;
    log_not_found off;
    access_log off;
}

location = /robots.txt {
    allow all;
    expires 1y;
    access_log off;
    log_not_found off;
}
location ~ ^/sitemap {
    if ($args != "") { return 301 $uri; }
    try_files $uri =404;

    allow all;
    expires 1d;
    access_log off;
    log_not_found off;
}

location ^~ /wp-content/uploads/ {
    if ($args != "") { return 301 $uri; }
    try_files $uri =404;

    expires 1y;
    access_log off;
    log_not_found off;
}

# find /www/wwwroot/ -type f -printf '%f\n' | grep -E '\.' | sed 's/.*\.//' | sort -u | grep -Eiv '^(php|webp|woff2|mp4|png|jpg|jpeg|svg|gif|eot|ttf|woff|js|css|ico|ini|log|conf|zip|py|po|mo|yaml|yml|csv|data|env|editorconfig|bcmap|ftl|htaccess|pot|md|markdown|sh|txt|scss|jsx|html|config|crt|xml|json|mjs)$'

location ~* \.(webp|woff2|mp4|png|jpg|jpeg|svg|gif|eot|ttf|woff)$ {
    expires 1y;
    access_log off;
    log_not_found off;
}
location ~* \.(js|css)$ {
    expires 1d;
    access_log off;
    log_not_found off;
}
location ~* \.(ico|ini|log|conf|zip|py|po|mo|yaml|yml|csv|data|env|editorconfig|bcmap|ftl|htaccess|pot|md|markdown|sh|txt|scss|jsx|html|config|crt|xml|json|mjs)$ {
    return 404;
    log_not_found off;
    access_log off;
}

server_tokens off; # Hide Nginx version in error messages and reponse headers.

# The X-XSS-Protection header has been deprecated by modern browsers and its use can introduce additional security issues on the client side.
# As such, it is recommended to set the header as X-XSS-Protection: 0 in order to disable the XSS Auditor, and not allow it to take the default behavior of the browser handling the response.
# Please use Content-Security-Policy instead.
add_header X-XSS-Protection "0" always;

add_header Content-Security-Policy "script-src * 'unsafe-inline' 'unsafe-eval'; object-src 'none'; worker-src 'none'; manifest-src 'none'; font-src 'self' https://fonts.gstatic.com; form-action 'self'; base-uri 'none';" always;
# Header always unset Access-Control-Allow-Origin
add_header X-Frame-Options "ALLOWALL" always;
add_header X-Content-Type-Options "nosniff" always;
# Header always unset Access-Control-Allow-Methods
add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), midi=(), ch-ua=(*), ch-ua-mobile=(*), ch-ua-arch=(*), ch-ua-platform=(*), ch-ua-model=(*), ch-ua-full-version=(*), ch-ua-platform-version=(*), ch-ua-bitness=(*), ch-ua-full-version-list=(*)" always;
add_header Referrer-Policy "strict-origin" always;

index index.php;

location / {
    try_files $uri /index.php?$args; # include the "?$args" part so non-default permalinks don't break when using query string
}
location ~ \.php$ {
    # php.ini cgi.fix_pathinfo = 0;

    include fastcgi.conf;
    fastcgi_intercept_errors on;

    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # Will otherwise default to /var/www

    fastcgi_pass unix:/run/php/php8.3-fpm.sock;
}