worker_processes auto; # one worker per CPU core
worker_rlimit_nofile 65535;

events {
	worker_connections ;
	# ulimit -n
	use epoll;
}

http {
	sendfile on; # Lets nginx send files directly from disk -> network
	tcp_nopush on; # Bundles HTTP response headers + file chunks into efficient packet sizes before sending
	tcp_nodelay on; # Disables Nagle's algorithm -> sends small packets immediately

	log_format custom_combined '$remote_addr - $remote_user [$time_local] '
	                           '"$request" $status $request_length $upstream_header_time $body_bytes_sent '
	                           '"$http_referer" "$http_user_agent"';

	access_log /var/log/nginx/access.log custom_combined;

	gzip on;
	gzip_comp_level 6; # 9 = max compression, heavy CPU
}