server {
    listen 127.0.0.1:9002;
    server_name localhost;

    location = /status {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9001;
        fastcgi_param SCRIPT_FILENAME /status;
    }
}

# ln -s /etc/nginx/sites-available/fpm-status.conf /etc/nginx/sites-enabled/