server {
    listen ssl;
    server_name _;

    root /usr/share;

    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;

    location /phpmyadmin {
        alias /usr/share/phpmyadmin/;
        index index.php;
    }

    location ~ ^/phpmyadmin/(.+\.php)$ {
        alias /usr/share/phpmyadmin/;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /usr/share/phpmyadmin/$1;

        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }
}

# ln -s /etc/nginx/sites-available/phpmyadmin.conf /etc/nginx/sites-enabled/