server {
    listen 443 ssl;
    listen [::]:443 ssl;
    # No Cloudflare "Proxied" = ERR_QUIC_PROTOCOL_ERROR

    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot

    server_name example.com;

    root /www/wwwroot/example.com;

    include /etc/nginx/global/wordpress.conf;
    include /etc/nginx/global/ssl.conf;
}

# rm /etc/nginx/sites-enabled/default
# ln -s /etc/nginx/sites-available/site.conf /etc/nginx/sites-enabled/
