# See memory usage per worker:
# ps -eo pid,rss,cmd | grep php-fpm
# PHP RAM / ^ = pm.max_children
# memory_limit * pm.max_children = max RAM usage

pm = 
pm.max_children = 

pm.start_servers = # How many PHP workers start immediately when PHP-FPM launches
pm.min_spare_servers = # Minimum idle workers PHP-FPM tries to keep ready
pm.max_spare_servers = # Maximum idle workers allowed

